export default [ { created_at: 'Tue Aug 02 00:16:01 +0000 2016',
    id: 760267877555507200,
    id_str: '760267877555507200',
    text: 'RT @kimakimberlin: Shop ethically with @Everlane, featuring the Cotton Poplin Shirt Dress – https://t.co/wOc276UruB https://t.co/7wHNJDXTBb',
    truncated: false,
    entities:
     { hashtags: [],
       symbols: [],
       user_mentions: [Object],
       urls: [Object],
       media: [Object] },
    extended_entities: { media: [Object] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 414932860,
       id_str: '414932860',
       name: 'Amanda Liz',
       screen_name: 'itsamandaliz',
       location: 'Pittsburgh',
       description: 'creative director & founder of Wallflower Design Co. (@wallflowerdc) i love Jesus and The Office. SNAPCHAT IS MY FAV: amannnnder',
       url: 'https://t.co/QlaOrnElLN',
       entities: [Object],
       protected: false,
       followers_count: 1041,
       friends_count: 395,
       listed_count: 15,
       created_at: 'Thu Nov 17 17:42:31 +0000 2011',
       favourites_count: 8647,
       utc_offset: -10800,
       time_zone: 'Atlantic Time (Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 8948,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/458377180439793664/CC5hAp6R.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/458377180439793664/CC5hAp6R.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/759521617391198208/_tP4HUsQ_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/759521617391198208/_tP4HUsQ_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/414932860/1459210795',
       profile_link_color: 'F58EA8',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Mon Aug 01 21:54:36 +0000 2016',
       id: 760232288319737900,
       id_str: '760232288319737856',
       text: 'Shop ethically with @Everlane, featuring the Cotton Poplin Shirt Dress – https://t.co/wOc276UruB https://t.co/7wHNJDXTBb',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       metadata: [Object],
       source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 1,
       favorite_count: 2,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Mon Aug 01 21:54:36 +0000 2016',
    id: 760232288319737900,
    id_str: '760232288319737856',
    text: 'Shop ethically with @Everlane, featuring the Cotton Poplin Shirt Dress – https://t.co/wOc276UruB https://t.co/7wHNJDXTBb',
    truncated: false,
    entities:
     { hashtags: [],
       symbols: [],
       user_mentions: [Object],
       urls: [Object],
       media: [Object] },
    extended_entities: { media: [Object] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 36468395,
       id_str: '36468395',
       name: 'kima kimberlin',
       screen_name: 'kimakimberlin',
       location: '',
       description: 'listening.',
       url: 'https://t.co/Uzu56PVvUI',
       entities: [Object],
       protected: false,
       followers_count: 1897,
       friends_count: 311,
       listed_count: 86,
       created_at: 'Wed Apr 29 20:22:58 +0000 2009',
       favourites_count: 15779,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: true,
       verified: false,
       statuses_count: 17058,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'FFFFFF',
       profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/378800000062360773/d39ea374d06b29895db04c387ef6a437.jpeg',
       profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/378800000062360773/d39ea374d06b29895db04c387ef6a437.jpeg',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/756991413670191104/8ZjUqErX_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/756991413670191104/8ZjUqErX_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/36468395/1470086786',
       profile_link_color: '006954',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: '262626',
       profile_text_color: 'A34469',
       profile_use_background_image: false,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 2,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' },
  { created_at: 'Thu Jul 28 17:01:51 +0000 2016',
    id: 758709061550428200,
    id_str: '758709061550428160',
    text: 'Everlane The Sleeveless Chambray Dress Size xs https://t.co/FgzSBP8vSN #boutique #fashion #forsale https://t.co/R8VhSlWUOt',
    truncated: false,
    entities:
     { hashtags: [Object],
       symbols: [],
       user_mentions: [],
       urls: [Object],
       media: [Object] },
    extended_entities: { media: [Object] },
    metadata: { iso_language_code: 'en', result_type: 'recent' },
    source: '<a href="http://dlvr.it" rel="nofollow">dlvr.it</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 4800884868,
       id_str: '4800884868',
       name: 'fleeknsleek',
       screen_name: 'fleeknsleek247',
       location: '',
       description: 'Clothing and accessories from top fashion designers Real Remy Hair Woman\'s Nails Fleeknsleek is the perfect place #fashion #style #clothing #shoes #handbags',
       url: 'https://t.co/8cbEUaLeGN',
       entities: [Object],
       protected: false,
       followers_count: 690,
       friends_count: 710,
       listed_count: 126,
       created_at: 'Sat Jan 23 03:07:37 +0000 2016',
       favourites_count: 223,
       utc_offset: -25200,
       time_zone: 'Pacific Time (US & Canada)',
       geo_enabled: false,
       verified: false,
       statuses_count: 191379,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/690733984255356932/RiQQnx1D_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/690733984255356932/RiQQnx1D_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/4800884868/1453542607',
       profile_link_color: '2B7BB9',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en' }
]